import { app, BrowserWindow, Tray, Menu, globalShortcut, screen, nativeImage } from 'electron'
import { join } from 'path'
import { initSandbox, loadConfig } from './config.js'
import { initLog } from './log.js'
import { setupIPC } from './ipc.js'
import { startVoicePipeline, stopVoicePipeline } from './voice/pipeline.js'
import { hasCredential } from './credentials.js'
import { chat } from './llm.js'
import { initAlerts, stopAlerts } from './alerts.js'

const isDev = process.env.NODE_ENV === 'development'

// App icon (arc reactor) — generated by scripts/gen-icon.mjs. __dirname is
// out/main at runtime, so resources/ sits two levels up.
const iconPath = join(__dirname, '../../resources/icon.png')

let overlay = null
let expandedPanel = null
let tray = null
let config = null

function getOverlayPosition() {
  const { workArea } = screen.getPrimaryDisplay()
  return {
    x: workArea.x + workArea.width - 396,
    y: workArea.y + workArea.height - 136
  }
}

function createOverlay() {
  const { x, y } = getOverlayPosition()

  overlay = new BrowserWindow({
    width: 380,
    height: 120,
    x,
    y,
    icon: iconPath,
    frame: false,
    transparent: true,
    alwaysOnTop: true,
    resizable: false,
    skipTaskbar: true,
    show: false,
    webPreferences: {
      preload: join(__dirname, '../preload/index.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false
    }
  })

  if (isDev && process.env.ELECTRON_RENDERER_URL) {
    // electron-vite sets this to the actual dev-server URL — never hardcode
    // the port: if 5173 is taken by another project's Vite, our windows
    // would render that app instead.
    overlay.loadURL(`${process.env.ELECTRON_RENDERER_URL}/?view=overlay`)
  } else {
    overlay.loadFile(join(__dirname, '../renderer/index.html'), {
      query: { view: 'overlay' }
    })
  }

  overlay.once('ready-to-show', () => overlay.show())
  overlay.on('closed', () => { overlay = null })
}

function createExpandedPanel() {
  if (expandedPanel) {
    expandedPanel.focus()
    return
  }

  expandedPanel = new BrowserWindow({
    width: 900,
    height: 700,
    minWidth: 700,
    minHeight: 500,
    icon: iconPath,
    title: `Jarvis — ${config?.sandbox?.root ?? 'C:\\jarvis\\'}`,
    show: false,
    webPreferences: {
      preload: join(__dirname, '../preload/index.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false
    }
  })

  if (isDev && process.env.ELECTRON_RENDERER_URL) {
    expandedPanel.loadURL(`${process.env.ELECTRON_RENDERER_URL}/?view=expanded`)
  } else {
    expandedPanel.loadFile(join(__dirname, '../renderer/index.html'), {
      query: { view: 'expanded' }
    })
  }

  expandedPanel.once('ready-to-show', () => expandedPanel.show())
  expandedPanel.on('closed', () => { expandedPanel = null })
}

function createTray() {
  // Arc-reactor icon, scaled down for the system tray. Falls back to an empty
  // image if the file is missing so the tray still appears.
  let icon = nativeImage.createFromPath(iconPath)
  icon = icon.isEmpty() ? nativeImage.createEmpty() : icon.resize({ width: 16, height: 16 })
  tray = new Tray(icon)

  const contextMenu = Menu.buildFromTemplate([
    { label: 'Open Jarvis', click: () => createExpandedPanel() },
    { label: 'Toggle Overlay', click: () => toggleOverlay() },
    { type: 'separator' },
    { label: 'Quit', click: () => app.quit() }
  ])

  tray.setToolTip('Jarvis')
  tray.setContextMenu(contextMenu)
  tray.on('click', () => toggleOverlay())
}

function toggleOverlay() {
  if (!overlay) return
  if (overlay.isVisible()) {
    overlay.hide()
  } else {
    overlay.show()
    overlay.focus()
  }
}

function broadcastToAll(channel, ...args) {
  [overlay, expandedPanel].forEach(win => {
    if (win && !win.isDestroyed()) {
      win.webContents.send(channel, ...args)
    }
  })
}

app.whenReady().then(async () => {
  try {
    config = await loadConfig()
    await initSandbox(config)
    await initLog(config)
    setupIPC({ config, broadcastToAll, createExpandedPanel })

    createTray()
    createOverlay()

    // Auto-open expanded panel on first run so the user can enter their API key
    if (!hasCredential('nvidia_api_key')) {
      createExpandedPanel()
    } else {
      // Validate the configured model exists — if not, open Integrations tab with a prompt
      validateModel(config, broadcastToAll, createExpandedPanel)
    }

    // Ctrl+Shift+J — toggle overlay visibility
    globalShortcut.register('CommandOrControl+Shift+J', toggleOverlay)

    // Ctrl+Shift+Space — activate listen mode
    globalShortcut.register('CommandOrControl+Shift+Space', () => {
      broadcastToAll('jarvis:activate-listen')
      startVoicePipeline({ config, broadcastToAll }).catch(console.error)
    })

    await startVoicePipeline({ config, broadcastToAll })
    initAlerts(config, broadcastToAll)
  } catch (err) {
    console.error('Startup error:', err)
  }
})

app.on('window-all-closed', () => {
  // Keep running in tray — do not quit
})

app.on('will-quit', () => {
  globalShortcut.unregisterAll()
  stopVoicePipeline()
  stopAlerts()
})

async function validateModel(config, broadcastToAll, createExpandedPanel) {
  try {
    // Use a real 1-token call — listing models doesn't catch models that 404 on inference
    await chat([{ role: 'user', content: 'hi' }], { maxTokens: 1, temperature: 0 })
  } catch (err) {
    console.warn(`Model validation failed (${err.status ?? err.message}) — opening model picker.`)
    createExpandedPanel()
    setTimeout(() => {
      broadcastToAll('jarvis:response', {
        text: `Model "${config.llm.model}" is not working (${err.status ?? 'error'}). Open the Integrations tab → Browse available models → select one → Use selected model.`,
        intent: 'ERROR'
      })
      broadcastToAll('jarvis:notify-open-tab', 'Integrations')
    }, 2000)
  }
}

export { broadcastToAll, createExpandedPanel }
